Function that iterates the Poincaré map
JuliaDynamics/ChaosTools.jl pull request #162
Opened 2021-03-17 10:17 UTC by awage

Hello, 

this is a function that iterates the Poincaré map step by step. It would be useful to track the orbit on the map. 

Best

2021-03-17 10:31 UTC, Datseris commented
Hi, thank you very much for the contribution, and welcome to the party! ;) 

I am a bit busy at the moment, but I promise to give a proper review as soon as I find the time.

One things that will be absolutely necessary before merging, which you can already do, is add a test suite. See how the `test` folder works and act accordingly. You will need to add a statement `export poincaremap` into the source code so that this function is accessible after `using ChaosTools`.

p.s.: I also saw you are working on Basin estimation which we would welcome in DynamicalSystems.jl as well.

2021-03-17 13:10 UTC, awage commented
Thanks for the message, I have already seen some bugs and clumsy errors. I will push a better code soon. 

We can talk later about my pet project of basin estimations.

2021-03-22 10:04 UTC, Datseris commented on src/orbitdiagrams/poincare.jl
> +	poincaremap(integ, planecrossing,  idxs, rootkw, Tmax)
Can you please rename this to `poincaremap!` as it is mutating the `integ`?

2021-03-22 10:06 UTC, Datseris commented on src/orbitdiagrams/poincare.jl
> +    return iter_f!, integ
I believe we can make this even more useful to the user by providing the following closure: a function that is called without any arguments and once called returns the next state on the Poincare map:

```
next_state = f()
```

you only need to define the return argment of `poincaremap` to do this process by wrapping `poincaremap!(integrator, ...)`

2021-03-22 13:16 UTC, awage commented on src/orbitdiagrams/poincare.jl
> +    return iter_f!, integ
I thought about that but I thought it would be useful to keep the control over the integrator in case a change of initial condition is needed. What about this: 

```jl 
# get the next state, f without argument
next_state = f()

# set the initial state, f with an initial vector: 
f(u0) 
```

I think it should be straightforward. What do you think?

2021-03-22 13:29 UTC, Datseris commented on src/orbitdiagrams/poincare.jl
> +    return iter_f!, integ
Perhaps even better would be that `f()` always returns the next state *from* the previous state, while `f(u0)` first sets the initial condition and then calls `f()`.

2021-03-23 11:11 UTC, Datseris commented
Thanks @awage , this looks very good to me. I only have some minor documentation comments, but I can do them quickly myself. One thing I am wondering is whether it makes sense for us to use this new code inside the existing `poincaresos` to reduce code duplication.

So the `poincaresos` will create the `poincaremap` and use this map to loop over the `integrator` as necessary.

What do you think? If you agree, would you like to do this change? In DynamicalSystems.jl we try hard (perhaps more than necessary) to have a clear and concise source code, and I think this can help here by eliminating code duplication.

2021-03-23 21:30 UTC, awage commented
I think this commit should do the trick. At least it does not seem to break anything. If you need more doc I can try to improve the docstrings.

2021-03-24 10:04 UTC, Datseris commented on src/orbitdiagrams/poincare.jl
> +end
I am sure that this is bad for performance. Can you please benchmark current `poincaresos` versus the `poincaresos` of this PR? It doesn't look like this would lead to good performance, because functional dispatch is done within `if` statements instead of multiple dispatch.

I think we might need to make a simple wrapper struct `PoincareMap` and create dispaches: `(pmap::PoincareMap)()` and `(pmap::PoincareMap)(u0)`.

2021-03-24 20:21 UTC, awage commented on src/orbitdiagrams/poincare.jl
> +end
I am not very proud of this code, and there is a loss in performance: 

poincaremap branch
@btime psos = poincaresos(ds, (2, 0.0), 10000.0, direction = +1)
  22.373 ms (57647 allocations: 3.30 MiB)

master branch
@btime psos = poincaresos(ds, (2, 0.0), 10000.0, direction = +1)
  20.502 ms (28833 allocations: 2.45 MiB)

I don't know how to do this wrapper. Is there a example somewhere you can point me to?

2021-03-24 20:50 UTC, awage commented
I figured out something although it is a bit sketchy. Good news is that there is an improvement in performance: 

`@btime psos = poincaresos(ds, (2, 0.0), 10000.0, direction = +1)
  18.872 ms (57647 allocations: 3.30 MiB)
`

That is slighlty better than the main branch. There are more allocations. Don't know why.

2021-03-25 12:37 UTC, Datseris commented
> That is slighlty better than the main branch. There are more allocations. Don't know why.

Is the "main" branch current `master`? If yes, can you please report the output of `master` as well?

2021-03-25 12:38 UTC, Datseris commented on src/orbitdiagrams/poincare.jl
> +end
This cannot stay like this. Every single field of this type must be explicitly type-parameterized. This brings a huge performance benefit the way it is right now.

2021-03-25 12:39 UTC, Datseris commented on src/orbitdiagrams/poincare.jl
> +end
This piece of code is no longer necessary, correct?

2021-03-25 23:58 UTC, awage commented
I did some benchmarks on the two branches: 
`poincaremap branch

@btime psos = poincaresos(ds, (2, 0.0), 40000.0, direction = +1)
    82.975 ms (159906 allocations: 11.14 MiB)

master branch
  @btime psos = poincaresos(ds, (2, 0.0), 40000.0, direction = +1)
    82.708 ms (134313 allocations: 10.36 MiB)
`

There is a slight advantage on master branch. On 40000 iterations it is not much but a little worse.

2021-03-26 10:21 UTC, Datseris requested changes

2021-03-26 10:21 UTC, Datseris commented on src/orbitdiagrams/poincare.jl
> +end
This is still incorrect within the Julia language. The fields are still not concretely typed. What you have to do is:

```suggestion
struct PoincareMap{I, P, A, R}
	integ::I
 	planecrossing::P
	Tmax::Float65
	i::A
	rootkw::R
end
```

2021-03-26 10:30 UTC, Datseris commented on src/orbitdiagrams/poincare.jl
> +end
See also: https://www.youtube.com/watch?v=Fi7Pf2NveH0

2021-03-26 10:31 UTC, Datseris commented on src/orbitdiagrams/poincare.jl
> +end
at 57 minutes

2021-03-27 15:43 UTC, Datseris commented
I wasn't entirely satisfied with the current design so I made some changes myself on what's happening. A main problem was what happened when the integrator passed the `Tmax`, where previously it wrongly returned the integrator's last state, which might have nothing to do with the actual section,.

I'm happy with current design and will merge if tests pass.

2021-03-27 16:47 UTC, Datseris commented
I also improved performance slightly by introducing a function barrier:
```
using ChaosTools, DynamicalSystemsBase
using BenchmarkTools

ds = Systems.roessler()
psos = poincaresos(ds, (2, 0.0), 1000.0)
@btime poincaresos(ds, (2, 0.0), 1000.0)

master: 
2.214 ms (2431 allocations: 153.22 KiB)

this pr:
2.140 ms (1747 allocations: 129.20 KiB)
```

2021-03-27 17:04 UTC, Datseris approved these changes

2021-03-27 17:07 UTC, merged

2021-03-28 21:06 UTC, awage commented
Wow! Thanks for the hard work! I will study these commits, I have still a lot to learn to make efficient code. 

A pleasure.

2021-03-28 21:25 UTC, Datseris commented
Contributions very welcome as always ;)