Fixes #84 with DyCA
JuliaDynamics/ChaosTools.jl pull request #165
Opened 2021-03-31 16:08 UTC by Anantha-Rao12

closes #84 
Hi! This PR contains an implementation of Dynamical Component Analysis based on the paper by Uhl et al. (2018) and [this](https://gist.github.com/Datseris/8121e5019071fe9e3cb9b1a0811ac26a) jupyter notebook originally written in python. I have added a file titled `dyca.jl` under `src/dyca.jl`. Please feel free to advise and comment. 

Checklist: 
- [x] I have read JuliaDynamics Contributing guidelines
- [ ] Clear and concise Documentation  
- [ ] Tests to check code breakage (if any) and performance

2021-03-31 20:07 UTC, Datseris commented on src/dyca.jl
> +function matrix_fdm_gradient(matrix,axis::Number)
Is the version with axis = 2 actually used anywhere...? If not, no reason to code it here. The smaller the source code the better it is for us.

2021-03-31 20:09 UTC, Datseris commented on src/dyca.jl
> +Source : https://arxiv.org/abs/1807.10629
Notice that the paper has been peer reviewed and published here: https://ieeexplore.ieee.org/document/8517024 . While not open access, we should still use this citation. In other documentation strings you will see that we do stuff like `[^Author1999]` to cite. You should do this here to, because it nicely groups citations at the end of the document!

2021-03-31 20:09 UTC, Datseris commented on src/dyca.jl
> +- `eig_thresold::float64` : the eigenvalue thresold for DyCA
I do not understand this. It seems to me that this function does not accept keyword arguments at all.

2021-03-31 20:10 UTC, Datseris commented on src/dyca.jl
> +Computes the Dynamical Component analysis matrix used for Dimensionality reduction. Here, we solve the main eigenvalue equation:
Dimensionality reduction => dimensionality reduction . It is a bit weird to capitalize the first word.

2021-03-31 20:11 UTC, Datseris commented on src/dyca.jl
> +where $C_0$ is the correlation matrix of the signal with itself, $C_1$ the correlation matrix of the signal with its derivative, and $C_2$ the correlation matrix of the derivative of the data with it
Unfortunately you cannot use `$` for mathematics in Documenter.jl... You have to use double backticks and the math environment, see here: https://github.com/JuliaDynamics/ChaosTools.jl/blob/master/src/chaosdetection/lyapunovs.jl#L171-L184

2021-04-01 05:07 UTC, Anantha-Rao12 commented on src/dyca.jl
> +function matrix_fdm_gradient(matrix,axis::Number)
Although I haven't seen any DyCA implementation using axis=2, I thought that the need might arise when someone wants to perform DyCA along axis 2. The [NumPy documentation](https://numpy.org/doc/stable/reference/generated/numpy.gradient.html) uses an axis argument so I thought of the same.  I can think of two solutions to this : 
1. Provide only the axis=1 option and remove any conditional for the axis variable. The user will then need to simply transpose their matrix to perform DyCA along axis2. This will rightly be mentioned in the Documentation
2. No changes to be made here but will be mentioned in the Documentation. 

What do you think @Datseris ? Based on your input, I will do the needful.

2021-04-01 05:08 UTC, Anantha-Rao12 commented on src/dyca.jl
> +Computes the Dynamical Component analysis matrix used for Dimensionality reduction. Here, we solve the main eigenvalue equation:
Sure. Will be done.

2021-04-01 06:01 UTC, Anantha-Rao12 commented on src/dyca.jl
> +where $C_0$ is the correlation matrix of the signal with itself, $C_1$ the correlation matrix of the signal with its derivative, and $C_2$ the correlation matrix of the derivative of the data with it
I made a commit that clears this issue.

2021-04-01 06:25 UTC, Anantha-Rao12 reviewed
Thanks for the message. I've looked into all the comments and added the corresponding changes. Please let me know if I missed out anything. 

> 
> Thank you for the contribution! I've left some documentation-related comments for now. Once this has tests as well, I will also check the algorithm in more detail (although this method is so trivially simple there isn't much to check, really)

Looking forward to future contributions. 
Ananth

2021-04-01 06:25 UTC, Anantha-Rao12 commented on src/dyca.jl
> +- `eig_thresold::float64` : the eigenvalue thresold for DyCA
Apologies. These are not keyword arguments.

2021-04-01 06:25 UTC, Anantha-Rao12 commented on src/dyca.jl
> +Source : https://arxiv.org/abs/1807.10629
Thanks for letting me know! I've looked into this and performed a commit. Let me know if the format of the citation is fine and any further changes.

2021-04-01 07:27 UTC, Datseris commented on src/dyca.jl
> +function matrix_fdm_gradient(matrix,axis::Number)
>  I thought that the need might arise when someone wants to perform DyCA along axis 2

They can simply transpose the matrix before passing it to DyCA.

Side comment: please rename `DyCA` to `dyca`. Would be useful for you to also have a look at Julia's [Naming Conventions](https://docs.julialang.org/en/v1/manual/style-guide/)

2021-04-01 07:27 UTC, Datseris commented
And what about the tests? Can you simply port the test they do for their synthetic data and/or EEG data?

2021-04-01 07:47 UTC, Anantha-Rao12 commented
Sure. I'll do that and share the notebook on gist.

2021-04-01 08:41 UTC, Datseris commented
> Sure. I'll do that and share the notebook on gist.

No, we need to have tests here, that are constantly checked. Please have a look at the `test` folder and model your tests accordingly.

2021-04-01 10:21 UTC, Anantha-Rao12 commented
> Please have a look at the `test` folder and model your tests accordingly.

Right! I completely forgot about the unit test, although I mentioned that in the checklist for the PR. I was wondering what would be a good test for `dyca().` For the EEG data, they just compared the results of DyCA with PCA, and I couldn't think of any suitable unit test for that. Will be glad if you could advise on this. 

Thank you.

2021-04-01 10:30 UTC, Datseris commented
From reading the paper I see

![image](https://user-images.githubusercontent.com/19669089/113281491-ec074e80-92e5-11eb-8ab8-cd860ce6c555.png)

The roessler system `Systems.roessler()` has 2 linear and 1 nonliner equation, thus if you apply this method to it, you should be able to see this.

2021-04-01 10:31 UTC, Datseris commented
Were you able to get the EEG data they used? Are they publicly available? If yes, do you get similar looking trajectories as they do?

2021-04-01 10:52 UTC, Anantha-Rao12 commented
>The roessler system `Systems.roessler()` has 2 linear and 1 nonliner equation, thus if you apply this method to it, you should be able to see this.

Great! I'll have a look at that and commit the test.  

> Were you able to get the EEG data they used? Are they publicly available?

Yes. It is available in the .zip file here: https://github.com/JuliaDynamics/ChaosTools.jl/files/3065748/dyca.zip  along with a notebook that implements `dyca()` in python.

> do you get similar looking trajectories as they do?

Suprisingly no. The python implementation gives only two eigenvectors for their threshold (Original had three). You can find the notebooks for julia and python here: https://gist.github.com/Anantha-Rao12/35b479b4798fa85abac2ebe0f1dbf06d

2021-04-01 11:08 UTC, Datseris commented
> Suprisingly no

Whaaaat! Perhaps you should contact the authors about this, stating that you couldn't reproduce their work (be sure to double check your code before doing that). I always do this in DynamicalSystems.jl. You would be surprised _how often nonlinear dynamics papers are not reproducible_...

2021-04-08 10:53 UTC, Datseris commented
@Anantha-Rao12 what's the status here? We should wrap up this one soon.

2021-04-08 11:12 UTC, Datseris commented
Have you also confirmed that your Julia gradient function gives the same number's as Numpys we applied to some given data e.g. read from a textfile?

2021-04-08 14:35 UTC, Anantha-Rao12 commented
Hi George. I've been trying to troubleshoot what's wrong with the Julia function here (not successful yet). The output for the EEG dataset seems to be different for me. I am getting two principal eigenvectors whereas the original implementation had 3 (which is correct and verified!). I have a hunch that this could be a problem with comparing complex values?

> Have you also confirmed that your Julia gradient function gives the same number's as numpys

Yes, both `np.gradient` and my `matrix_gradient` return the same matrices (I have tried different standard matrics) and both yield the same output.  However `matrix_gradient` works only along axis=1 (0 in python) since this is what is essentially needed for `dyca()`. 

> The roessler system Systems.roessler() has 2 linear and 1 nonliner equation, thus if you apply this method to it, you should be able to see this.

The IEEE paper did not mention anything about the eigenvalue threshold they use for the rossler system. Anyway I tried several values for the Rossler trajectory where some worked and some did not. I believe there is some issue with my code but I don't seem to find where. 

I have uploaded a notebook that summarises everything. Please have a look here: https://gist.github.com/Anantha-Rao12/7833573e44289b7dd26f1fed78270761

Thanks.

2021-04-09 09:10 UTC, Datseris commented
Have you contacted the authors yet to ask for the explicit threshoold they used for Roessler? This is something you need to familiarize yourself in doing when implementing papers of nonlinear dynamics.

2021-04-10 09:59 UTC, Anantha-Rao12 commented
Dear @Datseris. The issue is solved. I'm getting the same trajectories for the seizures dataset as used by the authors.

2021-04-10 17:57 UTC, Datseris commented
> Then the data was embedded in a 25-dimensional space with additional multiplicative Gaussian noise. We used an exemplary signal to noise ratio of 15dB.

They mean that they performed delay coordinates embedding, and added to the signal gaussian noise with std 15% of the signal's std. Are you familiar with delay embedding? In principle you simple have to call `embed(x, 15, 1)` on the timeseries `x`. See here for more: https://juliadynamics.github.io/DynamicalSystems.jl/dev/embedding/reconstruction/ 

> The issue is solved. The method is complete and works

Okay, so what was the problem?

> Another method to test I thought was to obtain a trajectory of the Rossler system from Systems.Rossler and check the number of dyca components for different values of eigenvalue-thresolds.

Yes, you should do this as well. There 2 out of the 3 components should be linear.

2021-04-11 11:59 UTC, Anantha-Rao12 commented
Hi @Datseris. I think the PR is complete now. Looking forward to your comments. 

> Okay, so what was the problem?

A simple bug. I was looking for an eigenvalue equation, not the generalized eigenvalue equation. 

> Are you familiar with delay embedding?

No actually, I was not familiar with delay embeddings. I read up the documentation (helped a lot!) and the Wikipedia page. Here are some points on the unit-test: 
1. Since we need to test the eigenvalues of `dyca()`, I added that to the return list of `dyca()` in `/src/dyca.jl`
```diff
- return  proj_mat, data * proj_mat
+ return eigenvalues, proj_mat, data * proj_mat
```

2. The test looks at eigenvalues (that are real) of the embedded system, counts the number of eigenvalues between (`eigenthresold`,1.0), and passes if the count is 2 (as discussed previously). I noticed that the count can fluctuate between [1,3] for some `eigenthresold` that is lower than 0.96 or are higher than 0.999 while it always passes (=2) for other thresholds. This maybe due to floating point errors :confused: 
This can be overcome for arbitrary thresholds [0.90,1.00], if we can do: 
```diff
- @test length(psum) == 2
+ @test length(psum) in (1,2,3)
```
Thanks. 
Ananth

2021-04-11 12:21 UTC, Datseris commented on test/dyca_tests.jl
> +            @test length(psum) == 2
Yes, you can use `in 1:3` instead here.

2021-04-11 12:21 UTC, Datseris commented on test/dyca_tests.jl
> +using Test
Where are the tests for the non-embedded Roessler system? Where you take the `ts`, make it into a `Matrix`, and plug it into `dyca`? Does it give you 2 linear eigenvals?

2021-04-11 12:23 UTC, Datseris commented on src/dyca.jl
> +Computes the Dynamical Component analysis matrix [^Uhl2018] used for dimensionality reduction. Here, we solve the generalised eigenvalue equation:
Computes -> compute.  Immediately after the first sentence, state what are the input arguments, and what are the return values.

I think you should have a look at other documentation strings of `ChaosTools` and modify this one accordingly.

2021-04-11 12:24 UTC, Datseris commented on src/dyca.jl
> +- `eig_thresold::float64` : the eigenvalue thresold for DyCA
Does not need a dedicated section, should be part of the opening statements of the docstring.

2021-04-11 12:24 UTC, Datseris commented on src/dyca.jl
> +- Data embeded by the projection matrix
same as above.

2021-04-11 12:25 UTC, Datseris commented on src/dyca.jl
> +where ``C_0`` is the correlation matrix of the signal with itself, ``C_1`` the correlation matrix of the signal with its derivative, and ``C_2`` the correlation matrix of the derivative of the data w
This stuff should be in a dedicated `## Description` section that gives appropriate info for the algorithm and its use.

2021-04-11 12:25 UTC, Datseris commented on src/dyca.jl
> +    dyca(data::Array,eig_thresold::float64)
```suggestion
    dyca(data::Array,eig_thresold::float64) -> eigenvalues, proj_mat, projected_data
```

2021-04-11 12:25 UTC, Datseris requested changes
Seems great to me, I only have comments for improving the docstring.

2021-04-11 12:32 UTC, Anantha-Rao12 commented on test/dyca_tests.jl
> +            psum = a[vec(thresold .< broadcast(abs,a) .< 1.0) .& vec(imag(a) .== 0)]
### Todo 
There is a bug here. It should be:
```diff
- psum = a[vec(thresold .< broadcast(abs,a) .< 1.0) .& vec(imag(a) .== 0)]
+ psum = eigenvals[vec(thresold .< broadcast(abs,eigenvals) .<= 1.0) .& vec(imag(eigenvals) .== 0)]

2021-04-11 12:38 UTC, Anantha-Rao12 commented on test/dyca_tests.jl
> +using Test
Yeah. I'm adding that.

2021-04-11 12:39 UTC, Datseris commented on test/dyca_tests.jl
> +            psum = a[vec(thresold .< broadcast(abs,a) .< 1.0) .& vec(imag(a) .== 0)]
You should start having more lines of code and simpler expressions. All these things are very hard to read.

2021-04-11 12:44 UTC, Datseris commented on test/dyca_tests.jl
> +            psum = a[vec(thresold .< broadcast(abs,a) .< 1.0) .& vec(imag(a) .== 0)]
Why write `broadcast(abs,eigenvals) ` instead of `abs.(eigenvals)`...?

2021-04-11 13:02 UTC, Anantha-Rao12 commented on src/dyca.jl
> +Computes the Dynamical Component analysis matrix [^Uhl2018] used for dimensionality reduction. Here, we solve the generalised eigenvalue equation:
Cool. Working on that now.

2021-04-11 14:35 UTC, Anantha-Rao12 commented on test/dyca_tests.jl
> +            @test length(psum) == 2
I used `in 0:4` and increased the range of threshold : `collect(0.90:0.01:0.995)`. The limiting cases of 0,4 occur at the extreme threshold values.

2021-04-11 14:36 UTC, Anantha-Rao12 commented on test/dyca_tests.jl
> +            psum = a[vec(thresold .< broadcast(abs,a) .< 1.0) .& vec(imag(a) .== 0)]
I dont know why I chose the former. Anyway its `abs.(eigenvals)` now.

2021-04-11 14:51 UTC, Datseris commented
Ops, one last thing we forgot before merging: please increment minor version in the Project.toml file, and add an entry in the CHANGELOG.md!

2021-04-11 14:59 UTC, Anantha-Rao12 commented
Umm. Are you sure that I should do it? (haven't done it before)
Anyway, I am thinking of the following:
# Project.toml : 
```diff
- version = "1.25.2"
+ version = "1.25.3"
```

# CHANGELOG.md
```diff
+ # 1.26
+ new function `dyca()` to perform Dynamical Component Analysis
```

2021-04-11 16:21 UTC, Datseris approved these changes

2021-04-11 16:22 UTC, Datseris commented
Have a look at https://semver.org , this is how we change versions in DynamicalSystems.jl 

This is good to go, I'll merge once tests pass.

2021-04-11 16:53 UTC, Anantha-Rao12 commented
Trying to understand what this `LoadError` means.  Any idea why `UndefVarError: dyca not defined` occurred? 
Also, (just realized), is it better to group all test sets in dyca_tests.jl under another testset, or is the current version fine?

2021-04-11 17:35 UTC, Datseris commented
without an `export` statement the names are not available when `using`.

2021-04-11 18:25 UTC, Datseris commented
@Anantha-Rao12 I'd like you to add more info into the `Decription` part of the docstring. While you state what numerical procedure is done, you don't actually say anything about the method, or why it is useful, or what it actually does.

Can you write a couple of sentences in your own words?

2021-04-11 18:26 UTC, Datseris commented
Also, there is no reason to end every line with `;` in Julia.

2021-04-12 19:11 UTC, Datseris commented on src/dyca.jl
> +
What are all these `<<<<<<<<` head stuff?

2021-04-12 19:19 UTC, Anantha-Rao12 commented on src/dyca.jl
> +
I actually have no idea. I thought it came when I pulled your docstring edits. I thought that it's a part of documenter.jl and left it as it is. If it's unrelated, then you can remove it.

2021-04-12 19:30 UTC, Datseris commented on src/dyca.jl
> +
You have to learn how to properly merge using git so that when there is a conflict you can take care of it. This happened bbecause we both pushed commits at the same branch. Please have a look at one of GitHub's videos or have a look at YouTube for "git merge conflicts".

2021-04-12 19:34 UTC, Datseris commented on src/dyca.jl
> +tool for the reduction of chaotic time-series.
@Anantha-Rao12 two comments: First, please do not use automatic wrapping on your text editor. Source code lines should never exceed 92 characters in width.

Second: the docstring now has more info, but I think we can improve it further yet. It sounds vague at the moment and does not convey the information it has to. Some examples:

* "leading to a classification of the underlying dynamics of high-dimensional" what is the classification? This is never stated. If you classify things, then you have to state the categories, otherwise what is the classification done for.
* "For a certain type of dynamics", which type? 
* "DyCA relies on a special deterministic model assumption" what assumption?

After reading the docstring I know that DyCa is a dimensionality reduction techinque but I don't know why I should use it. For example why is there no discussion of the linear / nonlinear subspaces?

2021-04-12 19:52 UTC, Anantha-Rao12 commented on src/dyca.jl
> +
Sure. Will do that. Thanks for letting me know!

2021-04-12 19:54 UTC, Anantha-Rao12 commented on src/dyca.jl
> +tool for the reduction of chaotic time-series.
Hmm. I understand. Working on it now! Will probably commit the changes after a few hours. Thanks for your detailed comments!

2021-04-13 09:24 UTC, Datseris commented on src/dyca.jl
> +methods like PCA or ICA that make a stochasticity assumption, DyCA relys on a determinacy
```suggestion
methods like PCA or ICA that make a stochasticity assumption, DyCA relies on a determinacy
```

2021-04-13 09:26 UTC, merged

2021-04-13 11:24 UTC, Anantha-Rao12 commented
Thank you @Datseris. It was a great experience to work on this issue. Learnt so many things! Looking forward to many more contributions! 

PS Any idea why the GALI tests keep failing?

2021-04-13 11:27 UTC, Datseris commented
me too!

nope. they do not fail locally for me. blasted CI.